// src/components/TodoList.jsx
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import axios from 'axios';
import TodoForm from './TodoForm';
import TodoItem from './TodoItem';

export default function TodoList() {
  const queryClient = useQueryClient();
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);
  const todosPerPage = 5;

  const { data: todos = [], isLoading, isError, error } = useQuery({
    queryKey: ['todos'],
    queryFn: async () => {
      const res = await axios.get('https://jsonplaceholder.typicode.com/todos');
      return res.data.slice(0,10); 
    }
  });

  // Mutations

const addTodoMutation = useMutation({
  mutationFn: async (title) => {
    const newTodo = {
      title,
      completed: false,
      userId: 1,
    };

    const res = await fetch('https://jsonplaceholder.typicode.com/todos', {
      method: 'POST',
      body: JSON.stringify(newTodo),
      headers: {
        'Content-Type': 'application/json',
      },
    });

    if (!res.ok) throw new Error('Failed to add todo');
    return res.json();
  },
  onSuccess: (data) => {
    alert('✅ New todo added!');
  queryClient.setQueryData(['todos'], (old) => [data, ...(old || [])]);
  },
});

  const deleteTodoMutation = useMutation({
    mutationFn: async (id) => {
      await axios.delete(`https://jsonplaceholder.typicode.com/todos/${id}`);
      return id;
    },
    onSuccess: (deletedId) => {
      queryClient.setQueryData(['todos'], (old) => old.filter((t) => t.id !== deletedId));
    },
  });

  const editTodoMutation = useMutation({
    mutationFn: async ({ id, title }) => {
      const res = await axios.put(`https://jsonplaceholder.typicode.com/todos/${id}`, { title });
      return res.data;
    },
    onSuccess: (updated) => {
      queryClient.setQueryData(['todos'], (old) =>
        old.map((t) => (t.id === updated.id ? updated : t))
      );
    },
  });

  const markCompletedMutation = useMutation({
    mutationFn: async ({ id, completed }) => {
      const res = await axios.patch(`https://jsonplaceholder.typicode.com/todos/${id}`, {
        completed: !completed,
      });
      return {id, completed: !completed };
    },
    onSuccess: (updated) => {
      queryClient.setQueryData(['todos'], (old) =>
        old.map((t) => (t.id === updated.id ? { ...t, completed: updated.completed } : t))
      );
    },
  });

  // Filters
  const filteredTodos = todos.filter((todo) => {
    const matchSearch = todo.title.toLowerCase().includes(searchTerm.toLowerCase());
    const matchFilter =
      filterStatus === 'all'
        ? true
        : filterStatus === 'completed'
        ? todo.completed
        : !todo.completed;
    return matchSearch && matchFilter;
  });

  // Pagination
  const totalPages = Math.ceil(filteredTodos.length / todosPerPage);
  const paginatedTodos = filteredTodos.slice(
    (currentPage - 1) * todosPerPage,
    currentPage * todosPerPage
  );

  // Handlers
  const handleAddTodo = (title) => addTodoMutation.mutate(title);
  const handleDelete = (id) => deleteTodoMutation.mutate(id);
  const handleEdit = (id, title) => editTodoMutation.mutate({ id, title });
  const handleMarkCompleted = (id, completed) =>
    markCompletedMutation.mutate({ id, completed });

  // UI
  if (isLoading) return <p role="status">Loading todos...</p>;
  if (isError) return <p role="alert">Error: {error.message}</p>;

  return (
    <main role="main" className="max-w-3xl mx-auto p-4">
      <header className="mb-6">
        <h1 className="text-2xl font-bold mb-4" tabIndex="0"></h1>

        <div className="flex flex-col md:flex-row gap-2" aria-label="Search and filter todos">
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => {
              setSearchTerm(e.target.value);
              setCurrentPage(1);
            }}
            aria-label="Search todos by title"
            placeholder="Search todos..."
            className="text-black border px-3 py-2 rounded w-full md:w-auto"
          />
          <select
            value={filterStatus}
            onChange={(e) => {
              setFilterStatus(e.target.value);
              setCurrentPage(1);
            }}
            aria-label="Filter by completion status"
            className=" bg-white text-black border px-3 py-2 rounded"
          >
            <option value="all">All</option>
            <option value="completed">Completed</option>
            <option value="incomplete">Incomplete</option>
          </select>
        </div>
      </header>

      <section aria-labelledby="todo-form-section" className="mb-6">
        <h2 id="todo-form-section" className=" sr-only"></h2>
        <TodoForm onAdd={handleAddTodo} />
      </section>

      <section aria-labelledby="todo-list-section">
        <h2 id="todo-list-section" className="sr-only">Todo Items</h2>

        {filteredTodos.length === 0 ? (
          <p>No todos found.</p>
        ) : (
          <>
            <ul className="space-y-4" role="list">
              {paginatedTodos.map((todo) => (
                <li key={todo.id} role="listitem">
                  <TodoItem
                    todo={todo}
                    onDelete={handleDelete}
                    onEdit={handleEdit}
                    onMarkCompleted={(id) => handleMarkCompleted(id, todo.completed)}
                  />
                </li>
              ))}
            </ul>

            {/* Pagination */}
            <nav
              aria-label="Pagination"
              className="mt-6 flex flex-wrap justify-center sm:justify-between items-center gap-4 text-sm"
            >
              <button
                onClick={() => setCurrentPage((p) => Math.max(p - 1, 1))}
                disabled={currentPage === 1}
                className="px-3 py-1 border rounded text-grey-500 disabled:text-gray-400 disabled:cursor-not-allowed"
              >
                ⬅ Prev
              </button>
              <span className="text-grey-600">
                Page {currentPage} of {totalPages}
              </span>
              <button
                onClick={() => setCurrentPage((p) => Math.min(p + 1, totalPages))}
                disabled={currentPage === totalPages}
                className="px-3 py-1 border rounded text-grey-500 disabled:text-grey-400 disabled:cursor-not-allowed"
              >
                Next ➡
              </button>
            </nav>
          </>
        )}
      </section>
    </main>
  );
}

// vue-app/src/components/TodoList.vue
<template>
  <main class="max-w-3xl mx-auto p-4">
    <header class="mb-6">
      <h1 class="text-2xl font-bold mb-4"></h1>

      <div class="flex flex-col md:flex-row gap-2" aria-label="Search and filter todos">
        <input
          type="text"
          v-model="searchTerm"
          @input="currentPage = 1"
          placeholder="Search todos..."
          class="text-black border px-3 py-2 rounded w-full md:w-auto"
        />
        <select
          v-model="filterStatus"
          @change="currentPage = 1"
          class="bg-white text-black border px-3 py-2 rounded"
        >
          <option value="all">All</option>
          <option value="completed">Completed</option>
          <option value="incomplete">Incomplete</option>
        </select>
      </div>
    </header>

    <section aria-labelledby="todo-form-section" class="mb-6">
      <TodoForm @add="handleAddTodo" />
    </section>

    <section aria-labelledby="todo-list-section">
      <h2 id="todo-list-section" class="sr-only">Todo Items</h2>

      <p v-if="filteredTodos.length === 0">No todos found.</p>

      <ul v-else class="space-y-4" role="list">
        <li v-for="todo in paginatedTodos" :key="todo.id" role="listitem">
          <TodoItem
            :todo="todo"
            @delete="handleDelete"
            @edit="handleEdit"
            @markCompleted="() => handleMarkCompleted(todo.id, todo.completed)"
          />
        </li>
      </ul>

      <nav
        v-if="filteredTodos.length > 0"
        aria-label="Pagination"
        class="mt-6 flex flex-wrap justify-center sm:justify-between items-center gap-4 text-sm"
      >
        <button
          @click="prevPage"
          :disabled="currentPage === 1"
          class="px-3 py-1 border rounded text-gray-500 disabled:text-gray-400 disabled:cursor-not-allowed"
        >
          ⬅ Prev
        </button>
        <span class="text-gray-600">Page {{ currentPage }} of {{ totalPages }}</span>
        <button
          @click="nextPage"
          :disabled="currentPage === totalPages"
          class="px-3 py-1 border rounded text-gray-500 disabled:text-gray-400 disabled:cursor-not-allowed"
        >
          Next ➡
        </button>
      </nav>
    </section>
  </main>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import axios from "axios";
import TodoForm from "./TodoForm.vue";
import TodoItem from "./TodoItem.vue";

interface Todo {
  id: number;
  title: string;
  completed: boolean;
  userId: number;
}

const todos = ref<Todo[]>([]);
const searchTerm = ref("");
const filterStatus = ref<"all" | "completed" | "incomplete">("all");
const currentPage = ref(1);
const todosPerPage = 5;

// Fetch Todos
const fetchTodos = async () => {
  const res = await axios.get<Todo[]>("https://jsonplaceholder.typicode.com/todos");
  todos.value = res.data.slice(0, 10);
};

onMounted(fetchTodos);

// Computed for filters
const filteredTodos = computed(() =>
  todos.value.filter((todo) => {
    const matchSearch = todo.title.toLowerCase().includes(searchTerm.value.toLowerCase());
    const matchFilter =
      filterStatus.value === "all"
        ? true
        : filterStatus.value === "completed"
        ? todo.completed
        : !todo.completed;
    return matchSearch && matchFilter;
  })
);

// Pagination
const totalPages = computed(() => Math.ceil(filteredTodos.value.length / todosPerPage));
const paginatedTodos = computed(() =>
  filteredTodos.value.slice(
    (currentPage.value - 1) * todosPerPage,
    currentPage.value * todosPerPage
  )
);

// Handlers
const handleAddTodo = async (title: string) => {
  const newTodo = { title, completed: false, userId: 1 };
  const res = await axios.post("https://jsonplaceholder.typicode.com/todos", newTodo);
  todos.value.unshift(res.data);
  alert("✅ New todo added!");
};

const handleDelete = async (id: number) => {
  await axios.delete(`https://jsonplaceholder.typicode.com/todos/${id}`);
  todos.value = todos.value.filter((t) => t.id !== id);
};

const handleEdit = async (payload: {id: number, newTitle: string}) => {
  const res = await axios.put(`https://jsonplaceholder.typicode.com/todos/${payload.id}`, { 
    title: payload.newTitle,
   });
  todos.value = todos.value.map((t) => (t.id === payload.id ? res.data : t));
};

const handleMarkCompleted = async (id: number, completed: boolean) => {
  const res = await axios.patch(`https://jsonplaceholder.typicode.com/todos/${id}`, {
    completed: !completed,
  });
  todos.value = todos.value.map((t) =>
    t.id === id ? { ...t, completed: res.data.completed } : t
  );
};

const prevPage = () => (currentPage.value = Math.max(currentPage.value - 1, 1));
const nextPage = () => (currentPage.value = Math.min(currentPage.value + 1, totalPages.value));
</script>
