// src/App.tsx
import { Outlet } from '@tanstack/react-router';

export default function App() {
  return (
    <div className= "min-h-screen bg-yellow-100 flex items-center  justify-center p-4">
     <main className="w-full max-w-3xl bg-black text-white rounded-lg p-6 shadow-xl ">
       <div className= " max-w-3xl mx-auto">
         <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-4 text-center">
           Todo App
         </h1>
       </div>

       <Outlet />
     </main>
    </div>
  );
}

// vue-app/src/App.vue
<template>
  <div id="app" class="min-h-screen bg-[#fef3c7] flex justify-center items-start py-10">
    <div class="bg-black text-white w-full max-w-xl md:max-w-3xl p-6 rounded-lg shadow-lg">
      <h1 class="text-2xl font-bold mb-6 text-center">Todo App</h1>
      <router-view />
    </div>
  </div>
</template>

<script lang="ts">
export default {
  name: "App",
};
</script>

<style>
body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
}
</style>
